### ISSUE TITLE
How To Run

### ISSUE THREAD

**Issue by agungsb** [Pajn/react-hero-transition#2]
Hi,

I've cloned the repo to my local. But, I don't see the way how to run the app. Would you please add the instruction to README.md? Thanks.

**Comment by amannn** [comment]
It should be possible by doing `cd example && yarn && yarn add react-hero-transition && yarn run start`.

Probably not the intended way, but this works.

**Comment by Pajn** [comment]
I have for some reason completely missed this issue, sorry for that!

The steps provided by amannn is probably the best ones right now (depending on if you might want to link instead). I will try to get time to figure out a nice flow and will then document it.

**Comment by Pajn** [comment]
The example should now be working with just `yarn && yarn start`. Sorry for the delay
